[package]
name = "project-name"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.10.0"
tree-sitter = "0.22.6"
tree-sitter-elixir = "0.2.0"
walkdir = "2.5.0"
